---
- name: Cisco SD-WAN Show Template Details using Sastre
  hosts: localhost
  gather_facts: true
  connection: local

  vars:
    # Use environment variables for credentials
    vmanage_host: "{{ lookup('env', 'VMANAGE_HOST') | default('vmanage-amfament-prod.sdwan.cisco.com') }}"
    vmanage_username: "{{ lookup('env', 'VMANAGE_USERNAME') | default('automation') }}"
    vmanage_password: "{{ lookup('env', 'VMANAGE_PASSWORD') | default('') }}"
    vmanage_port: "443"
    
    # Simple directory structure
    generated_dir: "{{ playbook_dir }}/generated"
    timestamp: "{{ ansible_date_time.epoch }}"
    output_file: "{{ generated_dir }}/template_details_{{ timestamp }}.json"

  tasks:
    - name: Validate environment variables are set
      fail:
        msg: "Required environment variable {{ item }} is not set"
      when: vars[item] == ""
      loop:
        - vmanage_host
        - vmanage_username
        - vmanage_password

    - name: Create generated directory
      file:
        path: "{{ generated_dir }}"
        state: directory
        mode: '0755'

    - name: Test vManage connectivity
      uri:
        url: "https://{{ vmanage_host }}/dataservice/system/device/controllers"
        method: GET
        user: "{{ vmanage_username }}"
        password: "{{ vmanage_password }}"
        force_basic_auth: yes
        validate_certs: false
        timeout: 60
        headers:
          Content-Type: "application/json"
      register: connectivity_test
      ignore_errors: true

    - name: Fail if connectivity test failed
      fail:
        msg: "Cannot connect to vManage at {{ vmanage_host }}"
      when: connectivity_test.status != 200

    - name: Show all feature templates
      command: >
        sastre
        --address {{ vmanage_host }}
        --port {{ vmanage_port }}
        --user {{ vmanage_username }}
        --password "{{ vmanage_password }}"
        --verbose
        show-template
        --workdir {{ generated_dir }}
        feature
      register: feature_templates
      environment:
        PYTHONHTTPSVERIFY: 0
        REQUESTS_CA_BUNDLE: ""

    - name: Show all device templates  
      command: >
        sastre
        --address {{ vmanage_host }}
        --port {{ vmanage_port }}
        --user {{ vmanage_username }}
        --password "{{ vmanage_password }}"
        --verbose
        show-template
        --workdir {{ generated_dir }}
        device
      register: device_templates
      environment:
        PYTHONHTTPSVERIFY: 0
        REQUESTS_CA_BUNDLE: ""

    - name: Save template details to file
      copy:
        content: |
          {
            "timestamp": "{{ ansible_date_time.iso8601 }}",
            "vmanage_host": "{{ vmanage_host }}",
            "feature_templates": {{ feature_templates.stdout | to_json }},
            "device_templates": {{ device_templates.stdout | to_json }}
          }
        dest: "{{ output_file }}"

    - name: Display completion message
      debug:
        msg: |
          Template details saved to: {{ output_file }}
          Feature templates command completed with return code: {{ feature_templates.rc }}
          Device templates command completed with return code: {{ device_templates.rc }}
